package com.siongriffiths.nppcdatavisualiser.data;


import javax.persistence.*;
import java.util.HashMap;
import java.util.Map;

/**
 * Created on 26/02/2016.
 *
 * @author Siôn Griffiths / sig2@aber.ac.uk
 *
 * Metadata is an entity class managed by Hibernate ORM persistence. The Metadata is a domain class
 * reprsenting data attributes that can be added and edited within the system. This class represents one or more tables
 * in the database
 */
@Entity
public class Metadata{

    /**
     * Autogenerated ID for each instance
     */
    private Integer id;

    /**
     * The data attribute map
     */
    private Map<String,String> dataAttributes;

    /**
     * Constructor ensuring dataAttributes is never null for a Metadata instance
     */
    public Metadata(){
        dataAttributes = new HashMap<>();
    }


    /**
     * Gets the instance ID. Annotated as Id or primary key in the database
     * @return the Metadata instance ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Integer getId() {
        return id;
    }

    /**
     * Sets the ID
     * @param id the id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Add a data attribute key value pair
     * @param key the key for the attribute
     * @param value the value for the attribute
     */
    public void addDataAttribute(String key, String value){
        dataAttributes.put(key,value);
    }


    /**
     * The ElementCollection annotation specifies that the annotated collection be persisted outside the table for this
     * Metadata class and in it's own linked table. This way its contained values can be represented as strings in the
     * database and queried via native query language on the database itself such as SQL.
     *
     * Gets the data attribute collection
     * @return the data attribute collection
     */
    @ElementCollection
    public Map<String, String> getDataAttributes() {
        return dataAttributes;
    }

    /**
     * Sets the data attribute collection
     * @param dataAttributes the data attribute collection
     */
    public void setDataAttributes(Map<String, String> dataAttributes) {
        this.dataAttributes = dataAttributes;
    }

}
