package com.siongriffiths.nppcdatavisualiser.data;

import javax.persistence.*;

/**
 * Created on 07/03/2016.
 *
 * @author Siôn Griffiths / sig2@aber.ac.uk
 *
 * TagData is an entity class managed by Hibernate ORM persistence. The TagData is a domain class
 * reprsenting tag annotations that can be added to entities within the system. This class represents a table in the
 * database and defines the unique constraint that only one TagData instance can exist with a given Tag content
 */
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"tag_content"}))
public class TagData {

    /**
     * Autogenerated ID for each instance
     */
    private long id;

    /**
     * Content of each tag
     */
    private String tagContent;

    /**
     * Constructors ensuring content is never null for a TagData
     */
    public TagData(){
        new TagData("");
    }
    public TagData(String content){
        tagContent = content;
    }

    /**
     * Gets the instance ID. Annotated as Id or primary key in the database
     * @return the TagData instance ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return id;
    }

    /**
     * Sets the ID
     * @param id the id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the content for this TagData instance. Column is named explicitly to ensure
     * accurate mapping of the defined unique constraint on the table
     * @return the tagContent
     */
    @Column(name = "tag_content")
    public String getTagContent() {
        return tagContent;
    }

    /**
     * Sets the content for a TagData
     * @param tagContent the content
     */
    public void setTagContent(String tagContent) {
        this.tagContent = tagContent;
    }


    /**
     * Autogenerated equals method by IntelliJ
     * @param o The object to check for equality
     * @return true if equals, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TagData tagData = (TagData) o;

        return id == tagData.id && tagContent.equals(tagData.tagContent);
    }

    /**
     * Autogenerated hashCode method by Intellij
     * @return hashcode for a TagData instance
     */
    @Override
    public int hashCode() {
        int result = (int) (id ^ (id >>> 32));
        result = 31 * result + tagContent.hashCode();
        return result;
    }
}
