package com.siongriffiths.nppcdatavisualiser.plants;

import javax.persistence.*;

/**
 * Created on 26/02/2016.
 *
 * @author Siôn Griffiths / sig2@aber.ac.uk
 *
 * PlantImage is an entity class managed by Hibernate ORM persistence. The PlantImage is a domain class
 * reprsenting a single image of a given Plant.
 * This class represents a table in the database and specifies the uniqueness constraint that a file path must be
 * unique to a single PlantImage instance
 */
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"filePath"}))
public class PlantImage {

    /**
     * Autogenerated ID for each instance
     */
    private long id;

    private String filePath;

    public PlantImage(){}

    /**
     * Constructor with filepath
     * @param filepath the filepath
     */
    public PlantImage(String filepath){
        this.filePath = filepath;
    }


    /**
     * Gets the instance ID. Annotated as Id or primary key in the database
     * @return the TagData instance ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return id;
    }

    /**
     * Sets the ID
     * @param id the id
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Gets the file path for this PlantImage instance. Column is named explicitly to ensure
     * accurate mapping of the defined unique constraint on the table
     * @return the file path
     */
    @Column
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the filepath for this PlantImage
     * @param filePath the file path
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }


}
